#############################################################################
# Makefile for building: RS-Video-Analyers
# Generated by qmake (2.01a) (Qt 4.6.3) on: Thu May 24 13:30:27 2012
# Project:  RS-Video-Analyers.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile RS-Video-Analyers.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtSql -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		AudioCode.cpp \
		AudioTab.cpp \
		CodeInterface.cpp \
		DatabaseAccessor.cpp \
		TreeItem.cpp \
		StartWindow.cpp \
		QueryData.cpp \
		VideoCode.cpp \
		MainWindow.cpp \
		VideoTab.cpp \
		TreeModel.cpp moc_AudioCode.cpp \
		moc_AudioTab.cpp \
		moc_StartWindow.cpp \
		moc_TreeModel.cpp \
		moc_VideoTab.cpp \
		moc_MainWindow.cpp \
		moc_VideoCode.cpp
OBJECTS       = main.o \
		AudioCode.o \
		AudioTab.o \
		CodeInterface.o \
		DatabaseAccessor.o \
		TreeItem.o \
		StartWindow.o \
		QueryData.o \
		VideoCode.o \
		MainWindow.o \
		VideoTab.o \
		TreeModel.o \
		moc_AudioCode.o \
		moc_AudioTab.o \
		moc_StartWindow.o \
		moc_TreeModel.o \
		moc_VideoTab.o \
		moc_MainWindow.o \
		moc_VideoCode.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		RS-Video-Analyers.pro
QMAKE_TARGET  = RS-Video-Analyers
DESTDIR       = 
TARGET        = RS-Video-Analyers

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: RS-Video-Analyers.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtSql.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile RS-Video-Analyers.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtSql.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile RS-Video-Analyers.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/RS-Video-Analyers1.0.0 || $(MKDIR) .tmp/RS-Video-Analyers1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/RS-Video-Analyers1.0.0/ && $(COPY_FILE) --parents AudioCode.h AudioTab.h CodeInterface.h DatabaseAccessor.h StartWindow.h QueryData.h TreeModel.h VideoTab.h MainWindow.h VideoCode.h TreeItem.h .tmp/RS-Video-Analyers1.0.0/ && $(COPY_FILE) --parents main.cpp AudioCode.cpp AudioTab.cpp CodeInterface.cpp DatabaseAccessor.cpp TreeItem.cpp StartWindow.cpp QueryData.cpp VideoCode.cpp MainWindow.cpp VideoTab.cpp TreeModel.cpp .tmp/RS-Video-Analyers1.0.0/ && (cd `dirname .tmp/RS-Video-Analyers1.0.0` && $(TAR) RS-Video-Analyers1.0.0.tar RS-Video-Analyers1.0.0 && $(COMPRESS) RS-Video-Analyers1.0.0.tar) && $(MOVE) `dirname .tmp/RS-Video-Analyers1.0.0`/RS-Video-Analyers1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/RS-Video-Analyers1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_AudioCode.cpp moc_AudioTab.cpp moc_StartWindow.cpp moc_TreeModel.cpp moc_VideoTab.cpp moc_MainWindow.cpp moc_VideoCode.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_AudioCode.cpp moc_AudioTab.cpp moc_StartWindow.cpp moc_TreeModel.cpp moc_VideoTab.cpp moc_MainWindow.cpp moc_VideoCode.cpp
moc_AudioCode.cpp: AudioCode.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) AudioCode.h -o moc_AudioCode.cpp

moc_AudioTab.cpp: CodeInterface.h \
		VideoCode.h \
		AudioCode.h \
		DatabaseAccessor.h \
		QueryData.h \
		AudioTab.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) AudioTab.h -o moc_AudioTab.cpp

moc_StartWindow.cpp: MainWindow.h \
		TreeItem.h \
		TreeModel.h \
		CodeInterface.h \
		VideoCode.h \
		AudioCode.h \
		DatabaseAccessor.h \
		QueryData.h \
		VideoTab.h \
		AudioTab.h \
		StartWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) StartWindow.h -o moc_StartWindow.cpp

moc_TreeModel.cpp: CodeInterface.h \
		VideoCode.h \
		AudioCode.h \
		DatabaseAccessor.h \
		QueryData.h \
		TreeModel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) TreeModel.h -o moc_TreeModel.cpp

moc_VideoTab.cpp: CodeInterface.h \
		VideoCode.h \
		AudioCode.h \
		DatabaseAccessor.h \
		QueryData.h \
		VideoTab.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) VideoTab.h -o moc_VideoTab.cpp

moc_MainWindow.cpp: TreeItem.h \
		TreeModel.h \
		CodeInterface.h \
		VideoCode.h \
		AudioCode.h \
		DatabaseAccessor.h \
		QueryData.h \
		VideoTab.h \
		AudioTab.h \
		MainWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MainWindow.h -o moc_MainWindow.cpp

moc_VideoCode.cpp: VideoCode.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) VideoCode.h -o moc_VideoCode.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp StartWindow.h \
		MainWindow.h \
		TreeItem.h \
		TreeModel.h \
		CodeInterface.h \
		VideoCode.h \
		AudioCode.h \
		DatabaseAccessor.h \
		QueryData.h \
		VideoTab.h \
		AudioTab.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

AudioCode.o: AudioCode.cpp AudioCode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AudioCode.o AudioCode.cpp

AudioTab.o: AudioTab.cpp AudioTab.h \
		CodeInterface.h \
		VideoCode.h \
		AudioCode.h \
		DatabaseAccessor.h \
		QueryData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AudioTab.o AudioTab.cpp

CodeInterface.o: CodeInterface.cpp CodeInterface.h \
		VideoCode.h \
		AudioCode.h \
		DatabaseAccessor.h \
		QueryData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CodeInterface.o CodeInterface.cpp

DatabaseAccessor.o: DatabaseAccessor.cpp DatabaseAccessor.h \
		QueryData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DatabaseAccessor.o DatabaseAccessor.cpp

TreeItem.o: TreeItem.cpp TreeItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TreeItem.o TreeItem.cpp

StartWindow.o: StartWindow.cpp StartWindow.h \
		MainWindow.h \
		TreeItem.h \
		TreeModel.h \
		CodeInterface.h \
		VideoCode.h \
		AudioCode.h \
		DatabaseAccessor.h \
		QueryData.h \
		VideoTab.h \
		AudioTab.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StartWindow.o StartWindow.cpp

QueryData.o: QueryData.cpp QueryData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QueryData.o QueryData.cpp

VideoCode.o: VideoCode.cpp VideoCode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VideoCode.o VideoCode.cpp

MainWindow.o: MainWindow.cpp MainWindow.h \
		TreeItem.h \
		TreeModel.h \
		CodeInterface.h \
		VideoCode.h \
		AudioCode.h \
		DatabaseAccessor.h \
		QueryData.h \
		VideoTab.h \
		AudioTab.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o MainWindow.cpp

VideoTab.o: VideoTab.cpp VideoTab.h \
		CodeInterface.h \
		VideoCode.h \
		AudioCode.h \
		DatabaseAccessor.h \
		QueryData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VideoTab.o VideoTab.cpp

TreeModel.o: TreeModel.cpp TreeItem.h \
		TreeModel.h \
		CodeInterface.h \
		VideoCode.h \
		AudioCode.h \
		DatabaseAccessor.h \
		QueryData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TreeModel.o TreeModel.cpp

moc_AudioCode.o: moc_AudioCode.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AudioCode.o moc_AudioCode.cpp

moc_AudioTab.o: moc_AudioTab.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AudioTab.o moc_AudioTab.cpp

moc_StartWindow.o: moc_StartWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_StartWindow.o moc_StartWindow.cpp

moc_TreeModel.o: moc_TreeModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TreeModel.o moc_TreeModel.cpp

moc_VideoTab.o: moc_VideoTab.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_VideoTab.o moc_VideoTab.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_VideoCode.o: moc_VideoCode.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_VideoCode.o moc_VideoCode.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

